### ISSUE TITLE
Switchboard Input Method Plug comes true

### ISSUE THREAD

**Issue by ryonakano** [bagjunggyu/Input-Method-Tab#1]
Let me tell you that now your "Input Method Tab" idea is in real. :tada:

I saw your proposal and ideas in this repository long before, and it really made me feel like to make your idea real in the future. At that time I have no experience of programming.

After I learned Vala, which is widely used in elementary OS components, published an app to AppCenter, and got some knowledge of these kinds of things, I began to work to make "Input Method Tab" real.

![Screenshot](https://user-images.githubusercontent.com/26003928/62422559-705b9580-b6ef-11e9-83f7-7e3c0c357c26.png)

This is the screenshot of the current state of Switchboard Input Method Plug. Although it's still work in progress, the bellow features have been supported:

* Adding already installed input method engines
* Removing input method engines (not deleting, just removing)

These are exactly what we can do in IBus Preferences, but I'm going to support the following features (which IBus Preferences does not have!) in the future:

* Deleting input method engines
* Installing input method engines

My project is at https://github.com/ele-l10n-cjk/switchboard-plug-inputmethod. I would appreciate if you would post Issues of ideas or proposals or submit PRs :wink:

You can install this Plug in the way as described [here](https://github.com/ele-l10n-cjk/switchboard-plug-inputmethod#installation). Plugs built by outside developers are not accepted to publish in AppCenter, so I think adding PPA is the best way, like elementary-tweaks.

Thank you very much for your great idea, if you had never made it public here, I would have never built this Plug! :heart: :blush:

**Comment by bagjunggyu** [comment]
WoW!!
WoW!!
Thank you very much ^___^
Thank you very much for your work and I hope it could be shown to us soon.

**Comment by ryonakano** [comment]
I made another project for CJK l10n in elementary OS: [Wingpanel Input Method Indicator](https://github.com/ele-l10n-cjk/wingpanel-indicator-inputmethod).

This indicator shows all IMEs you've added in Switchboard Input Method Plug or `ibus-setup` and allows you to choose current IME you want to use.

This is how it looks like:

![Screenshot from 2020-03-22 06 31 41](https://user-images.githubusercontent.com/26003928/77236969-ef61f780-6c06-11ea-8f2b-0210ae767cd4.png)

I would appreciate it if you would be interested in this indicator. You can install it to your system as described in [README](https://github.com/ele-l10n-cjk/wingpanel-indicator-inputmethod#for-users).

**Comment by ryonakano** [comment]
![Screenshot from 2020-05-24 07-57-31](https://user-images.githubusercontent.com/26003928/82742078-46658380-9d94-11ea-91e6-2ba6cd7052b2.png)

The functions provided in this Plug were [merged into the official Keyboard Plug](https://github.com/elementary/switchboard-plug-keyboard/pull/287), which is more suitable to call as the original name you called: Input Method "Tab". This change should be available on the next version of elementary OS. Thank you again for your ideas and attention!

**Comment by bagjunggyu** [comment]
WoW!! This is so amazing 👍 
Finally, We made it.
Thank you for your efforts for all of it.
^_^
